### ISSUE TITLE
COCO model weights and semantic segmentation results

### ISSUE THREAD

**Issue by Darren-pfchen** [Eli-YiLi/PMM#11]
Hello, I am very interested in your work. I want to do some further study. Can you share the model weights and semantic segmentation results on COCO dataset.
Thanks a lot !

**Comment by Eli-YiLi** [comment]
Hi, you can find the weights of coco from the shared link of BaiduYun in the readme (folder "WSSS/released_weights/")

The results are not kept when I left the company. You can predict results from the released weights.

You can refer to "https://github.com/Eli-YiLi/WSSS_MMSeg/blob/main/tools/run_wsss.sh", the config with _cp.py will save the predictions. Note, coco does not use cyclic mask, thus you need to add follow code to config "https://github.com/Eli-YiLi/WSSS_MMSeg/blob/main/configs/pspnet_wsss/pspnet_wres38-d8_40kx32_coco.py".

test_cfg = dict(mode='slide', crop_size=(512, 512), stride=(480, 480), crf=True,
                pred_output_path='data/coco2014/results')

Then inference with follow command for wres38. (If you run the code on a server instead of a cluster, use dist_test as slurm_test)

bash tools/slurm_test.sh PARTITION python configs/pspnet_wsss/pspnet_wres38-d8_40kx32_coco.py ${ckpts[0]} 8
