### ISSUE TITLE
Need your help for detailed ppmg metrics!

### ISSUE THREAD

**Issue by lh-zhu** [Eli-YiLi/PMM#13]
Greetings!

We are making some incremental work on your PMM. The PPMG's performance is amazing! But we find that your provided pseudo masks for [VOC2012](https://onedrive.live.com/?authkey=%21ACgB0g238YxuTxs&cid=B9423297729DF909&id=B9423297729DF909%21110&parId=B9423297729DF909%21109&o=OneUp) and [COCO2014](https://pan.baidu.com/s/1GL3zXZuapuXmH9E7Xy8-Fg#list/path=%2FWSSS) do not contain pseudo masks of val set. And we wonder about more details of the PPMG pseudo masks on val set for these two datasets. We will appreciate it if you could answer some of our questions!

1) If the 'pseudo_mask.tar' in the [onedrive](https://onedrive.live.com/?authkey=%21ACgB0g238YxuTxs&cid=B9423297729DF909&id=B9423297729DF909%21110&parId=B9423297729DF909%21109&o=OneUp) correspond to the 61.49% val mIoU in Tab. 2 of the paper? 
2) If the answer to 1) is not, what is the mIoU of the 'pseudo_mask.tar' on the val set? 
3) what is the mIoU of the 'ppmg_coco.zip' in the [baiduyun](https://pan.baidu.com/s/1GL3zXZuapuXmH9E7Xy8-Fg#list/path=%2FWSSS) on the val set? 
4) If you are busy, could you provide the pseudo masks on val sets of VOC2012 and COCO2014 to us?

Thanks again for your patience and help!

**Comment by Eli-YiLi** [comment]
The released code is slightly different from the initial experimental code in some minor points. So the val results maybe different from the report results. I remember the result is little higher than the paper (not certain). Since I have left the company without raw data, like val pseudo masks. So, It's suggested to reproduce the val pseudo mask as the generation of train process by yourself. Sorry for that, but I think it's not very complex.

**Comment by lh-zhu** [comment]
Thank you!
